# Generated by Django 5.1.6 on 2025-05-02 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='blockedDevs',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='blockedGames',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followedDevs',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followedGames',
            field=models.TextField(default='[]'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=255)),
                ('genres', models.TextField(default='[]')),
                ('gameImage', models.TextField(default='placeholder')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.developer')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsTitle', models.CharField(max_length=255)),
                ('newsContent', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.game')),
            ],
        ),
    ]
